name: Publish UPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upm-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release for OpenUPM
      id: create_release
      uses: quabug/create-upm-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGE_NAME: ${{ env.UNITY_PACKAGE_NAME }}
        PACKAGE_ID: ${{ env.UNITY_PACKAGE_ID }}
      with:
        target: main
        upm_tag_prefix: v
        upm_package_path: Packages/$PACKAGE_ID
        create_unitypackage: true
        unitypackage_name: $PACKAGE_NAME
