name: publish-nuget-package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_PROJECT_DIR: ${{ env.DOTNET_PROJECT_DIR }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: |
        cd $DOTNET_PROJECT_DIR
        dotnet pack -c Release -o out
    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./$DOTNET_PROJECT_DIR/out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
